# Generated by Django 3.2.7 on 2021-12-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0004_soldier_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soldiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
