# Generated by Django 3.2.7 on 2021-12-20 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0006_user_opponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='opponent',
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposed_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='singlePlayer.team')),
            ],
        ),
        migrations.AddField(
            model_name='general',
            name='as_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generals', related_query_name='generals', to='singlePlayer.opponent'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='as_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', related_query_name='soldiers', to='singlePlayer.opponent'),
        ),
    ]
