# Generated by Django 3.2.7 on 2021-12-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0008_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='opponent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to='singlePlayer.opponent'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='general',
            name='as_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generals', related_query_name='generals', to='singlePlayer.opponent'),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='opposed_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to='singlePlayer.team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='as_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers', related_query_name='soldiers', to='singlePlayer.opponent'),
        ),
    ]
