# Generated by Django 3.2.7 on 2021-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0009_auto_20211221_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='killed_soldiers',
            new_name='killed_units',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='killed_soldiers',
            new_name='killed_units',
        ),
        migrations.AddField(
            model_name='general',
            name='max_life',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='general',
            name='on_battle_k_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soldier',
            name='max_life',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='soldier',
            name='on_battle_k_u',
            field=models.IntegerField(default=0),
        ),
    ]
