# Generated by Django 3.2.7 on 2021-12-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0010_auto_20211221_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.URLField(max_length=5000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
