# Generated by Django 3.2.7 on 2021-12-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0011_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.IntegerField(default=5),
        ),
    ]
