# Generated by Django 3.2.7 on 2021-12-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlePlayer', '0012_product_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponent',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to='singlePlayer.team'),
        ),
    ]
